# config/services.yaml
services:
  _defaults:
    autowire: true

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: [ 'command' ]

  AdventOfCode\:
    resource: '../src/*'

  AdventOfCode\App:
    public: true
    arguments:
      - !tagged_iterator command